<a href="https://colab.research.google.com/github/MinaAlberDS/Codveda-Internship/blob/master/Level%201/Task%201/Web_scrapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scrapping, and collecting the data

### Collecting the Real Estates links

In [1]:
# Import the needed libraries
import requests
from bs4 import BeautifulSoup
import time
import pandas as pd
# Make the function which will get the real_estates links
def real_estates_links(pages:int,verbose:bool=True):
    """
    Scrapes real estate listing links from real estate ate.gov.eg.

    Args:
        pages: An integer representing the number of pages to scrape.
        verbose: A boolean indicating whether to print the progress of scraping each page.

    Returns:
        A list of strings, where each string is a URL to a real estate listing.
        :param pages: An integer representing the number of pages to scrape.
        :param verbose: A boolean indicating whether to print the progress of scraping each page.

    """
    base_url = r"https://realestate.gov.eg/ar/search/%D8%B4%D8%B1%D8%A7%D8%A1?page={}"
    links_list = [] # links list
    for page in range(1,pages+1): # This for loop to get the 9 real_estates links in each page
        start_time = time.perf_counter() # start a stop watch for each page
        page_url = base_url.format(page) # Set the page url from the baseline url using f-string or format
        response = requests.get(page_url) # Get the response of the page url
        if response.status_code == 200: # check if the page can be scrapped or not
          soap = BeautifulSoup(response.content, "html.parser") # set the soop variable to scrape the links from the page html
          real_estates = soap.find_all("div", class_="col-md-4")[3:] # get the real_estates links

          for real_estate in real_estates: # Add the real_estates links to the links list
              link = r"https://realestate.gov.eg" + real_estate.find("a")["href"] # Set the real_estate url
              links_list.append(link) # add it to the links list
          end_time = time.perf_counter() # stop the timer
          elapsed = end_time - start_time # count the elapsed time
          if verbose: # if the verbose is true, it will show some useful information about each page
              print(f"Page: {page} links have been appended in {elapsed:.4f}s")
        else: # if the page cannot be scraped
          print(f"failed to scrape this Page: {page} with code: {response.status_code}")
        time.sleep(0.5)
    return links_list # finally retrun the links list

In [2]:
links = real_estates_links(50, True) # running our function with 350 pages, and verbose = True

Page: 1 links have been appended in 2.5953s
Page: 2 links have been appended in 2.4979s
Page: 3 links have been appended in 3.0739s
Page: 4 links have been appended in 2.4732s
Page: 5 links have been appended in 2.4727s
Page: 6 links have been appended in 2.5073s
Page: 7 links have been appended in 2.5300s
Page: 8 links have been appended in 2.4963s
Page: 9 links have been appended in 2.5290s
Page: 10 links have been appended in 2.5319s

KeyboardInterrupt:

In [ ]:
len(links)

450

|We have 504 real_estate to scrape

In [ ]:
import json
# export the real_estates links to a json file
with open("../data/raw/Links.json", "w") as links_json:
    json.dump(links, links_json, indent =4)

In [ ]:
# import the json file links to scrap them
with open("../data/raw/Links.json", "r") as links_json:
  links = json.load(links_json)
# show the results
links[:5]

['https://realestate.gov.eg/ar/property-details/mamsha-avenue/new-administrative-capital/cairo/building-maa15b-floor-1-unit-maa15b14-mamsha-avenue-new-administrative-capital-cairo-cairo-egypt/E189166',
 'https://realestate.gov.eg/ar/property-details/new-garden-city/new-administrative-capital/cairo/building-g883-floor-mezzanine-unit-g883mr10-new-garden-city-new-administrative-capital-cairo-cairo-egypt/E377964',
 'https://realestate.gov.eg/ar/property-details/maspero-mall/cairo/cairo/building-mm-floor-ground-floor-unit-mmrtg24b-maspero-mall-cairo-cairo-cairo-egypt/E110528',
 'https://realestate.gov.eg/ar/property-details/alamain-(latin-district)/north-coast/alexandria/building-a03-floor-3-unit-z05-cl08-a03-x4-03-05-alamain-(latin-district)-north-coast-alexandria-egypt/E375962',
 'https://realestate.gov.eg/ar/property-details/zahya/mansoura/dakahlia/building-zh3m71-unit-zh3m71-zahya-mansoura-(m)-dakahlia-egypt/E110258']

### Collect the real_estates data

In [ ]:
import json

def collect_real_estate_data(real_estates_links:list, verbose:bool=True, except_2025:bool=False):
    """
    Scrapes real estate data from a list of real estate listing URLs.
    Args:
        real_estates_links: A list of strings, where each string is a URL to a real estate listing.
        verbose: A boolean indicating whether to print the progress of scraping each real estate listing.
        except_2025: A boolean indicating whether to exclude listings built in 2025.
    Returns:
        A dictionary containing lists of scraped data for each real estate listing.
    """
    # Initialize a dictionary to store data for all real_estates
    all_real_estates_data = {
        'name': [],
        'price': [],
        'property_type': [],
        'bedrooms': [],
        'bathrooms': [],
        'sqm': [],
        'year_built': [],
        'features': [],
        'city': [],
        'governorate': [],
        'address': [],
        'description': []
    }

    # Open the JSON file in append mode outside the loop
    with open("../data/processed/real_estates_data.json", "w") as real_estates_data:
        # Initialize the JSON file with an empty list
        json.dump([], real_estates_data)


    for i, real_estate_link in enumerate(real_estates_links): # get the data from each real_estate
        try:
            real_estate_response = requests.get(real_estate_link) # Get the request of the real_estate link
            real_estate_soop = BeautifulSoup(real_estate_response.content, "html.parser") # make the real_estate soop

            real_estate_div = real_estate_soop.find_all("div", class_= "propertySpecs_spec_box__xLU5D")
            if len(real_estate_div) > 0:
                year_built = real_estate_div[4].find_all("span")[1]

                if except_2025 and year_built and year_built.text.strip() not in ["2022","2023", "2024"]:
                    if verbose:
                        print(f"Skipping real_estate {i+1}/{len(real_estates_links)} built in 2025")
                    continue  # Skip this real_estate if it's built in 2025

                # Extract data, handling potential missing elements
                name = real_estate_soop.find("h6", class_= "propertyInfo_name__bs0i7")
                all_real_estates_data['name'].append(name.get_text(strip=True) if name else None)

                price = real_estate_soop.find("p", class_ = "propertyInfo_price__8ecPp")
                all_real_estates_data['price'].append(price.text.strip() if price else None)

                property_type = real_estate_div[0].find("span")
                all_real_estates_data['property_type'].append(property_type.text.strip() if property_type else None)

                # Extract bedroom, bathroom, sqm, and year built if available

                bedroom = real_estate_div[1].find_all("span")[1]
                all_real_estates_data['bedrooms'].append(bedroom.text.strip() if bedroom else None)
                bathroom = real_estate_div[2].find_all("span")[1]
                all_real_estates_data['bathrooms'].append(bathroom.text.strip() if bathroom else None)
                sqm = real_estate_div[3].find_all("span")[1]
                all_real_estates_data['sqm'].append(sqm.text.strip() if sqm else None)
                all_real_estates_data['year_built'].append(year_built.text.strip() if year_built else None)

            else:
                # Append None for property type and other specs if the main div is not found
                all_real_estates_data['property_type'].append(None)
                all_real_estates_data['bedrooms'].append(None)
                all_real_estates_data['bathrooms'].append(None)
                all_real_estates_data['sqm'].append(None)
                all_real_estates_data['year_built'].append(None)


            real_estate_features = []
            real_estate_features_dv = real_estate_soop.find_all("div", class_ = "col-md-6")
            for real_estate_feature in real_estate_features_dv:
                feature_text = real_estate_feature.find("h2")
                if feature_text:
                    real_estate_features.append(feature_text.get_text(strip=True))
            all_real_estates_data['features'].append(real_estate_features) # Append the list of features


            real_estate_city_div = real_estate_soop.find_all("div", class_= "propertyData_address_info_row__up8MX")
            if len(real_estate_city_div) > 2:
                city = real_estate_city_div[1].find_all("p")
                all_real_estates_data['city'].append(city[1].get_text(strip=True) if len(city) > 1 else None)

                governorate = real_estate_city_div[2].find_all("p")
                all_real_estates_data['governorate'].append(governorate[1].get_text(strip=True) if len(governorate) > 1 else None)
            else:
                # Append None if city and governorate details are not found
                all_real_estates_data['city'].append(None)
                all_real_estates_data['governorate'].append(None)


            address_div = real_estate_soop.find("div", class_="propertyData_address_info_row__up8MX propertyData_address_row__vZiYP")
            if address_div:
                address = address_div.find_all("p")
                all_real_estates_data['address'].append(address[1].get_text(strip=True) if len(address) > 1 else None)
            else:
                # Append None if address is not found
                all_real_estates_data['address'].append(None)

            description_div = real_estate_soop.find("div", class_= "propertyData_property_long_description__mAJPf")
            if description_div:
                 # Extract text from each paragraph tag and join them
                 paragraph_texts = [p.get_text(strip=True) for p in description_div.find_all("p")]
                 full_description = "".join(paragraph_texts)
                 all_real_estates_data['description'].append(full_description)
            else:
                # Append None if description is not found
                all_real_estates_data['description'].append(None)


            # Append the data of the current real_estate to the JSON file
            with open("../data/processed/real_estates_data.json", "r+") as real_estates_data:
                data = json.load(real_estates_data)
                data.append({key: all_real_estates_data[key][-1] for key in all_real_estates_data})  # Append the last added data
                real_estates_data.seek(0) # the begining of the file
                json.dump(data, real_estates_data, indent=4) # Add the real_estate data
                real_estates_data.truncate() # The beining of the file

            if verbose:
                print(f"Scraped data for real_estate {i+1}/{len(real_estates_links)}")

        except Exception as e:
            print(f"Error scraping {real_estate_link}: {e}")
            # Append None for all fields if an error occurs during scraping
            for key in all_real_estates_data:
                all_real_estates_data[key].append(None)

        time.sleep(0.5)
    return all_real_estates_data

#### Except 2025 real_estates

In [ ]:
real_estates_data = collect_real_estate_data(links, except_2025=True)
real_estates_data

Skipping real_estate 1/450 built in 2025
Skipping real_estate 2/450 built in 2025
Scraped data for real_estate 3/450
Skipping real_estate 4/450 built in 2025
Scraped data for real_estate 5/450
Skipping real_estate 6/450 built in 2025
Skipping real_estate 7/450 built in 2025
Skipping real_estate 8/450 built in 2025
Skipping real_estate 9/450 built in 2025
Skipping real_estate 10/450 built in 2025
Scraped data for real_estate 11/450
Scraped data for real_estate 12/450
Scraped data for real_estate 13/450
Skipping real_estate 14/450 built in 2025
Skipping real_estate 15/450 built in 2025
Skipping real_estate 16/450 built in 2025
Skipping real_estate 17/450 built in 2025
Skipping real_estate 18/450 built in 2025
Skipping real_estate 19/450 built in 2025
Skipping real_estate 20/450 built in 2025
Skipping real_estate 21/450 built in 2025
Skipping real_estate 22/450 built in 2025
Skipping real_estate 23/450 built in 2025
Skipping real_estate 24/450 built in 2025
Scraped data for real_estate 25/450
Skipping real_estate 26/450 built in 2025
Skipping real_estate 27/450 built in 2025
Skipping real_estate 28/450 built in 2025
Skipping real_estate 29/450 built in 2025
Skipping real_estate 30/450 built in 2025
Skipping real_estate 31/450 built in 2025
Scraped data for real_estate 32/450
Skipping real_estate 33/450 built in 2025
Skipping real_estate 34/450 built in 2025
Scraped data for real_estate 35/450
Skipping real_estate 36/450 built in 2025
Skipping real_estate 37/450 built in 2025
Skipping real_estate 38/450 built in 2025
Skipping real_estate 39/450 built in 2025
Skipping real_estate 40/450 built in 2025
Skipping real_estate 41/450 built in 2025
Skipping real_estate 42/450 built in 2025
Skipping real_estate 43/450 built in 2025
Skipping real_estate 44/450 built in 2025
Skipping real_estate 45/450 built in 2025
Skipping real_estate 46/450 built in 2025
Skipping real_estate 47/450 built in 2025
Skipping real_estate 48/450 built in 2025
Skipping real_estate 49/450 built in 2025
Skipping real_estate 50/450 built in 2025
Scraped data for real_estate 51/450
Skipping real_estate 52/450 built in 2025
Skipping real_estate 53/450 built in 2025
Skipping real_estate 54/450 built in 2025
Skipping real_estate 55/450 built in 2025
Skipping real_estate 56/450 built in 2025
Skipping real_estate 57/450 built in 2025
Skipping real_estate 58/450 built in 2025
Skipping real_estate 59/450 built in 2025
Skipping real_estate 60/450 built in 2025
Skipping real_estate 61/450 built in 2025
Skipping real_estate 62/450 built in 2025
Scraped data for real_estate 63/450
Scraped data for real_estate 64/450
Skipping real_estate 65/450 built in 2025
Skipping real_estate 66/450 built in 2025
Skipping real_estate 67/450 built in 2025
Skipping real_estate 68/450 built in 2025
Skipping real_estate 69/450 built in 2025
Skipping real_estate 70/450 built in 2025
Skipping real_estate 71/450 built in 2025
Skipping real_estate 72/450 built in 2025
Skipping real_estate 73/450 built in 2025
Skipping real_estate 74/450 built in 2025
Skipping real_estate 75/450 built in 2025
Scraped data for real_estate 76/450
Skipping real_estate 77/450 built in 2025
Scraped data for real_estate 78/450
Skipping real_estate 79/450 built in 2025
Skipping real_estate 80/450 built in 2025
Scraped data for real_estate 81/450
Skipping real_estate 82/450 built in 2025
Skipping real_estate 83/450 built in 2025
Skipping real_estate 84/450 built in 2025
Skipping real_estate 85/450 built in 2025
Skipping real_estate 86/450 built in 2025
Scraped data for real_estate 87/450
Skipping real_estate 88/450 built in 2025
Skipping real_estate 89/450 built in 2025
Skipping real_estate 90/450 built in 2025
Skipping real_estate 91/450 built in 2025
Skipping real_estate 92/450 built in 2025
Skipping real_estate 93/450 built in 2025
Scraped data for real_estate 94/450
Skipping real_estate 95/450 built in 2025
Skipping real_estate 96/450 built in 2025
Skipping real_estate 97/450 built in 2025
Skipping real_estate 98/450 built in 2025
Skipping real_estate 99/450 built in 2025
Skipping real_estate 100/450 built in 2025
Skipping real_estate 101/450 built in 2025
Skipping real_estate 102/450 built in 2025
Scraped data for real_estate 103/450
Skipping real_estate 104/450 built in 2025
Skipping real_estate 105/450 built in 2025
Skipping real_estate 106/450 built in 2025
Skipping real_estate 107/450 built in 2025
Skipping real_estate 108/450 built in 2025
Scraped data for real_estate 109/450
Skipping real_estate 110/450 built in 2025
Skipping real_estate 111/450 built in 2025
Skipping real_estate 112/450 built in 2025
Skipping real_estate 113/450 built in 2025
Skipping real_estate 114/450 built in 2025
Scraped data for real_estate 115/450
Skipping real_estate 116/450 built in 2025
Skipping real_estate 117/450 built in 2025
Skipping real_estate 118/450 built in 2025
Skipping real_estate 119/450 built in 2025
Skipping real_estate 120/450 built in 2025
Skipping real_estate 121/450 built in 2025
Skipping real_estate 122/450 built in 2025
Skipping real_estate 123/450 built in 2025
Scraped data for real_estate 124/450
Skipping real_estate 125/450 built in 2025
Scraped data for real_estate 126/450
Skipping real_estate 127/450 built in 2025
Skipping real_estate 128/450 built in 2025
Skipping real_estate 129/450 built in 2025
Skipping real_estate 130/450 built in 2025
Scraped data for real_estate 131/450
Scraped data for real_estate 132/450
Skipping real_estate 133/450 built in 2025
Scraped data for real_estate 134/450
Scraped data for real_estate 135/450
Scraped data for real_estate 136/450
Skipping real_estate 137/450 built in 2025
Skipping real_estate 138/450 built in 2025
Skipping real_estate 139/450 built in 2025
Skipping real_estate 140/450 built in 2025
Skipping real_estate 141/450 built in 2025
Skipping real_estate 142/450 built in 2025
Skipping real_estate 143/450 built in 2025
Skipping real_estate 144/450 built in 2025
Scraped data for real_estate 145/450
Skipping real_estate 146/450 built in 2025
Skipping real_estate 147/450 built in 2025
Skipping real_estate 148/450 built in 2025
Skipping real_estate 149/450 built in 2025
Skipping real_estate 150/450 built in 2025
Skipping real_estate 151/450 built in 2025
Skipping real_estate 152/450 built in 2025
Skipping real_estate 153/450 built in 2025
Skipping real_estate 154/450 built in 2025
Skipping real_estate 155/450 built in 2025
Skipping real_estate 156/450 built in 2025
Skipping real_estate 157/450 built in 2025
Skipping real_estate 158/450 built in 2025
Skipping real_estate 159/450 built in 2025
Skipping real_estate 160/450 built in 2025
Skipping real_estate 161/450 built in 2025
Skipping real_estate 162/450 built in 2025
Skipping real_estate 163/450 built in 2025
Skipping real_estate 164/450 built in 2025
Skipping real_estate 165/450 built in 2025
Skipping real_estate 166/450 built in 2025
Skipping real_estate 167/450 built in 2025
Skipping real_estate 168/450 built in 2025
Skipping real_estate 169/450 built in 2025
Skipping real_estate 170/450 built in 2025
Skipping real_estate 171/450 built in 2025
Skipping real_estate 172/450 built in 2025
Skipping real_estate 173/450 built in 2025
Skipping real_estate 174/450 built in 2025
Skipping real_estate 175/450 built in 2025
Skipping real_estate 176/450 built in 2025
Skipping real_estate 177/450 built in 2025
Skipping real_estate 178/450 built in 2025
Skipping real_estate 179/450 built in 2025
Skipping real_estate 180/450 built in 2025
Skipping real_estate 181/450 built in 2025
Skipping real_estate 182/450 built in 2025
Skipping real_estate 183/450 built in 2025
Skipping real_estate 184/450 built in 2025
Skipping real_estate 185/450 built in 2025
Scraped data for real_estate 186/450
Skipping real_estate 187/450 built in 2025
Skipping real_estate 188/450 built in 2025
Skipping real_estate 189/450 built in 2025
Skipping real_estate 190/450 built in 2025
Skipping real_estate 191/450 built in 2025
Scraped data for real_estate 192/450
Skipping real_estate 193/450 built in 2025
Skipping real_estate 194/450 built in 2025
Skipping real_estate 195/450 built in 2025
Skipping real_estate 196/450 built in 2025
Skipping real_estate 197/450 built in 2025
Skipping real_estate 198/450 built in 2025
Skipping real_estate 199/450 built in 2025
Skipping real_estate 200/450 built in 2025
Skipping real_estate 201/450 built in 2025
Skipping real_estate 202/450 built in 2025
Skipping real_estate 203/450 built in 2025
Scraped data for real_estate 204/450
Skipping real_estate 205/450 built in 2025
Skipping real_estate 206/450 built in 2025
Skipping real_estate 207/450 built in 2025
Skipping real_estate 208/450 built in 2025
Skipping real_estate 209/450 built in 2025
Scraped data for real_estate 210/450
Skipping real_estate 211/450 built in 2025
Skipping real_estate 212/450 built in 2025
Skipping real_estate 213/450 built in 2025
Skipping real_estate 214/450 built in 2025
Skipping real_estate 215/450 built in 2025
Skipping real_estate 216/450 built in 2025
Scraped data for real_estate 217/450
Skipping real_estate 218/450 built in 2025
Skipping real_estate 219/450 built in 2025
Scraped data for real_estate 220/450
Skipping real_estate 221/450 built in 2025
Skipping real_estate 222/450 built in 2025
Skipping real_estate 223/450 built in 2025
Skipping real_estate 224/450 built in 2025
Skipping real_estate 225/450 built in 2025
Skipping real_estate 226/450 built in 2025
Skipping real_estate 227/450 built in 2025
Scraped data for real_estate 228/450
Skipping real_estate 229/450 built in 2025
Skipping real_estate 230/450 built in 2025
Skipping real_estate 231/450 built in 2025
Skipping real_estate 232/450 built in 2025
Skipping real_estate 233/450 built in 2025
Skipping real_estate 234/450 built in 2025
Skipping real_estate 235/450 built in 2025
Scraped data for real_estate 236/450
Skipping real_estate 237/450 built in 2025
Scraped data for real_estate 238/450
Scraped data for real_estate 239/450
Skipping real_estate 240/450 built in 2025
Skipping real_estate 241/450 built in 2025
Scraped data for real_estate 242/450
Skipping real_estate 243/450 built in 2025
Skipping real_estate 244/450 built in 2025
Skipping real_estate 245/450 built in 2025
Skipping real_estate 246/450 built in 2025
Skipping real_estate 247/450 built in 2025
Skipping real_estate 248/450 built in 2025
Skipping real_estate 249/450 built in 2025
Skipping real_estate 250/450 built in 2025
Skipping real_estate 251/450 built in 2025
Skipping real_estate 252/450 built in 2025
Scraped data for real_estate 253/450
Skipping real_estate 254/450 built in 2025
Skipping real_estate 255/450 built in 2025
Skipping real_estate 256/450 built in 2025
Skipping real_estate 257/450 built in 2025
Skipping real_estate 258/450 built in 2025
Skipping real_estate 259/450 built in 2025
Skipping real_estate 260/450 built in 2025
Skipping real_estate 261/450 built in 2025
Skipping real_estate 262/450 built in 2025
Skipping real_estate 263/450 built in 2025
Skipping real_estate 264/450 built in 2025
Skipping real_estate 265/450 built in 2025
Skipping real_estate 266/450 built in 2025
Skipping real_estate 267/450 built in 2025
Skipping real_estate 268/450 built in 2025
Skipping real_estate 269/450 built in 2025
Skipping real_estate 270/450 built in 2025
Skipping real_estate 271/450 built in 2025
Skipping real_estate 272/450 built in 2025
Skipping real_estate 273/450 built in 2025
Skipping real_estate 274/450 built in 2025
Skipping real_estate 275/450 built in 2025
Skipping real_estate 276/450 built in 2025
Skipping real_estate 277/450 built in 2025
Skipping real_estate 278/450 built in 2025
Skipping real_estate 279/450 built in 2025
Skipping real_estate 280/450 built in 2025
Skipping real_estate 281/450 built in 2025
Skipping real_estate 282/450 built in 2025
Skipping real_estate 283/450 built in 2025
Skipping real_estate 284/450 built in 2025
Skipping real_estate 285/450 built in 2025
Skipping real_estate 286/450 built in 2025
Skipping real_estate 287/450 built in 2025
Skipping real_estate 288/450 built in 2025
Scraped data for real_estate 289/450
Skipping real_estate 290/450 built in 2025
Scraped data for real_estate 291/450
Skipping real_estate 292/450 built in 2025
Skipping real_estate 293/450 built in 2025
Skipping real_estate 294/450 built in 2025
Skipping real_estate 295/450 built in 2025
Skipping real_estate 296/450 built in 2025
Skipping real_estate 297/450 built in 2025
Skipping real_estate 298/450 built in 2025
Skipping real_estate 299/450 built in 2025
Skipping real_estate 300/450 built in 2025
Skipping real_estate 301/450 built in 2025
Skipping real_estate 302/450 built in 2025
Skipping real_estate 303/450 built in 2025
Skipping real_estate 304/450 built in 2025
Skipping real_estate 305/450 built in 2025
Skipping real_estate 306/450 built in 2025
Scraped data for real_estate 307/450
Skipping real_estate 308/450 built in 2025
Skipping real_estate 309/450 built in 2025
Skipping real_estate 310/450 built in 2025
Skipping real_estate 311/450 built in 2025
Skipping real_estate 312/450 built in 2025
Scraped data for real_estate 313/450
Skipping real_estate 314/450 built in 2025
Scraped data for real_estate 315/450
Skipping real_estate 316/450 built in 2025
Scraped data for real_estate 317/450
Skipping real_estate 318/450 built in 2025
Skipping real_estate 319/450 built in 2025
Skipping real_estate 320/450 built in 2025
Skipping real_estate 321/450 built in 2025
Skipping real_estate 322/450 built in 2025
Skipping real_estate 323/450 built in 2025
Skipping real_estate 324/450 built in 2025
Skipping real_estate 325/450 built in 2025
Scraped data for real_estate 326/450
Skipping real_estate 327/450 built in 2025
Skipping real_estate 328/450 built in 2025
Skipping real_estate 329/450 built in 2025
Skipping real_estate 330/450 built in 2025
Skipping real_estate 331/450 built in 2025
Skipping real_estate 332/450 built in 2025
Skipping real_estate 333/450 built in 2025
Skipping real_estate 334/450 built in 2025
Scraped data for real_estate 335/450
Skipping real_estate 336/450 built in 2025
Skipping real_estate 337/450 built in 2025
Skipping real_estate 338/450 built in 2025
Skipping real_estate 339/450 built in 2025
Skipping real_estate 340/450 built in 2025
Skipping real_estate 341/450 built in 2025
Skipping real_estate 342/450 built in 2025
Skipping real_estate 343/450 built in 2025
Skipping real_estate 344/450 built in 2025
Skipping real_estate 345/450 built in 2025
Skipping real_estate 346/450 built in 2025
Skipping real_estate 347/450 built in 2025
Skipping real_estate 348/450 built in 2025
Scraped data for real_estate 349/450
Skipping real_estate 350/450 built in 2025
Skipping real_estate 351/450 built in 2025
Skipping real_estate 352/450 built in 2025
Skipping real_estate 353/450 built in 2025
Scraped data for real_estate 354/450
Skipping real_estate 355/450 built in 2025
Skipping real_estate 356/450 built in 2025
Skipping real_estate 357/450 built in 2025
Skipping real_estate 358/450 built in 2025
Skipping real_estate 359/450 built in 2025
Skipping real_estate 360/450 built in 2025
Skipping real_estate 361/450 built in 2025
Skipping real_estate 362/450 built in 2025
Scraped data for real_estate 363/450
Skipping real_estate 364/450 built in 2025
Skipping real_estate 365/450 built in 2025
Skipping real_estate 366/450 built in 2025
Skipping real_estate 367/450 built in 2025
Skipping real_estate 368/450 built in 2025
Skipping real_estate 369/450 built in 2025
Skipping real_estate 370/450 built in 2025
Skipping real_estate 371/450 built in 2025
Skipping real_estate 372/450 built in 2025
Skipping real_estate 373/450 built in 2025
Skipping real_estate 374/450 built in 2025
Skipping real_estate 375/450 built in 2025
Skipping real_estate 376/450 built in 2025
Skipping real_estate 377/450 built in 2025
Skipping real_estate 378/450 built in 2025
Skipping real_estate 379/450 built in 2025
Scraped data for real_estate 380/450
Skipping real_estate 381/450 built in 2025
Skipping real_estate 382/450 built in 2025
Skipping real_estate 383/450 built in 2025
Skipping real_estate 384/450 built in 2025
Skipping real_estate 385/450 built in 2025
Skipping real_estate 386/450 built in 2025
Skipping real_estate 387/450 built in 2025
Skipping real_estate 388/450 built in 2025
Skipping real_estate 389/450 built in 2025
Skipping real_estate 390/450 built in 2025
Scraped data for real_estate 391/450
Skipping real_estate 392/450 built in 2025
Scraped data for real_estate 393/450
Skipping real_estate 394/450 built in 2025
Skipping real_estate 395/450 built in 2025
Skipping real_estate 396/450 built in 2025
Scraped data for real_estate 397/450
Skipping real_estate 398/450 built in 2025
Skipping real_estate 399/450 built in 2025
Skipping real_estate 400/450 built in 2025
Skipping real_estate 401/450 built in 2025
Skipping real_estate 402/450 built in 2025
Skipping real_estate 403/450 built in 2025
Skipping real_estate 404/450 built in 2025
Skipping real_estate 405/450 built in 2025
Skipping real_estate 406/450 built in 2025
Skipping real_estate 407/450 built in 2025
Scraped data for real_estate 408/450
Skipping real_estate 409/450 built in 2025
Skipping real_estate 410/450 built in 2025
Skipping real_estate 411/450 built in 2025
Skipping real_estate 412/450 built in 2025
Skipping real_estate 413/450 built in 2025
Skipping real_estate 414/450 built in 2025
Skipping real_estate 415/450 built in 2025
Skipping real_estate 416/450 built in 2025
Skipping real_estate 417/450 built in 2025
Skipping real_estate 418/450 built in 2025
Skipping real_estate 419/450 built in 2025
Skipping real_estate 420/450 built in 2025
Scraped data for real_estate 421/450
Scraped data for real_estate 422/450
Skipping real_estate 423/450 built in 2025
Skipping real_estate 424/450 built in 2025
Skipping real_estate 425/450 built in 2025
Skipping real_estate 426/450 built in 2025
Scraped data for real_estate 427/450
Skipping real_estate 428/450 built in 2025
Skipping real_estate 429/450 built in 2025
Scraped data for real_estate 430/450
Skipping real_estate 431/450 built in 2025
Scraped data for real_estate 432/450
Scraped data for real_estate 433/450
Skipping real_estate 434/450 built in 2025
Skipping real_estate 435/450 built in 2025
Scraped data for real_estate 436/450
Skipping real_estate 437/450 built in 2025
Skipping real_estate 438/450 built in 2025
Scraped data for real_estate 439/450
Skipping real_estate 440/450 built in 2025
Skipping real_estate 441/450 built in 2025
Scraped data for real_estate 442/450
Skipping real_estate 443/450 built in 2025
Skipping real_estate 444/450 built in 2025
Scraped data for real_estate 445/450
Skipping real_estate 446/450 built in 2025
Skipping real_estate 447/450 built in 2025
Scraped data for real_estate 448/450
Skipping real_estate 449/450 built in 2025
Skipping real_estate 450/450 built in 2025

{'name': ['Maspero mall',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Maspero Business Tower Nile Heights',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Maspero Business Tower Nile Heights',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Maspero Business Tower Nile Heights',
  'Maspero Business Tower Nile Heights',
  'Zahya',
  'Zahya',
  'Zahya',
  'Maspero mall',
  'Maspero Business Tower Nile Heights',
  'Zahya',
  'Zahya',
  'Maspero Business Tower Nile Heights',
  'Zahya',
  'Maspero Business Tower Nile Heights',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Maspero Business Tower Nile Heights',
  'Maspero Business Tower Nile Heights',
  'Zahya',
  'Zahya',
  'Maspero Business Tower Nile Heights',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Maspero Business Tower Nile Heights',
  'Zahya',
  'Zahya',
  'Zahya',
  'Zahya',
  'Maspero Business Tower Nile Heights',
  'Maspero mall'],
 'price': ['17,886,000 ج م',
  '17,536,000 ج م',
  '22,024,000 ج م',
  '10,249,000 ج م',
  '17,478,000 ج م',
  '9,850,000 ج م',
  '18,389,000 ج م',
  '10,197,000 ج م',
  '9,962,000 ج م',
  '10,612,000 ج م',
  '6,846,000 ج م',
  '21,758,000 ج م',
  '10,649,000 ج م',
  '10,226,000 ج م',
  '11,114,000 ج م',
  '10,495,000 ج م',
  '10,511,000 ج م',
  '9,857,000 ج م',
  '24,478,000 ج م',
  '11,856,000 ج م',
  '11,266,000 ج م',
  '22,024,000 ج م',
  '10,557,000 ج م',
  '10,578,000 ج م',
  '11,502,000 ج م',
  '9,787,000 ج م',
  '11,400,000 ج م',
  '10,557,000 ج م',
  '10,898,000 ج م',
  '11,506,000 ج م',
  '11,856,000 ج م',
  '11,567,000 ج م',
  '10,154,000 ج م',
  '11,690,000 ج م',
  '28,692,000 ج م',
  '12,529,000 ج م',
  '10,844,000 ج م',
  '12,640,000 ج م',
  '12,529,000 ج م',
  '13,099,000 ج م',
  '11,506,000 ج م',
  '10,844,000 ج م',
  '12,393,000 ج م',
  '10,538,000 ج م',
  '17,616,000 ج م',
  '12,192,000 ج م',
  '11,856,000 ج م',
  '68,727,000 ج م',
  '10,452,000 ج م',
  '11,114,000 ج م',
  '12,529,000 ج م',
  '22,026,000 ج م',
  '11,375,000 ج م',
  '10,649,000 ج م',
  '11,028,000 ج م',
  '10,467,000 ج م',
  '24,478,000 ج م',
  '10,542,000 ج م',
  '13,099,000 ج م',
  '6,846,000 ج م',
  '11,890,000 ج م',
  '10,612,000 ج م',
  '10,209,000 ج م',
  '10,669,000 ج م',
  '12,026,000 ج م',
  '28,692,000 ج م'],
 'property_type': ['تجاري, مبنى البيع بالتجزئة / مول',
  'سكني, فيلا',
  'سكني, فيلا',
  'سكني, توين هاوس',
  'سكني, فيلا',
  'سكني, توين هاوس',
  'سكني, فيلا',
  'سكني, توين هاوس',
  'سكني, تاون هاوس',
  'سكني, توين هاوس',
  'تجاري, مكتب',
  'سكني, فيلا',
  'سكني, تاون هاوس',
  'سكني, تاون هاوس',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'سكني, فيلا',
  'تجاري, مكتب',
  'سكني, توين هاوس',
  'سكني, فيلا',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'سكني, تاون هاوس',
  'تجاري, مكتب',
  'تجاري, مكتب',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'تجاري, مبنى البيع بالتجزئة / مول',
  'تجاري, مكتب',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'تجاري, مكتب',
  'سكني, توين هاوس',
  'تجاري, مكتب',
  'سكني, توين هاوس',
  'سكني, تاون هاوس',
  'سكني, توين هاوس',
  'سكني, فيلا',
  'سكني, توين هاوس',
  'تجاري, مكتب',
  'تجاري, محل تجاري',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'تجاري, مكتب',
  'سكني, فيلا',
  'سكني, توين هاوس',
  'سكني, تاون هاوس',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'سكني, فيلا',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'تجاري, مكتب',
  'سكني, تاون هاوس',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'سكني, توين هاوس',
  'تجاري, مكتب',
  'تجاري, مبنى البيع بالتجزئة / مول'],
 'bedrooms': ['0',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '0',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '0',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '0',
  '0',
  '3',
  '3',
  '3',
  '0',
  '0',
  '3',
  '3',
  '0',
  '3',
  '0',
  '3',
  '3',
  '3',
  '3',
  '3',
  '0',
  '0',
  '3',
  '3',
  '0',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '3',
  '0',
  '3',
  '3',
  '3',
  '3',
  '0',
  '0'],
 'bathrooms': ['0',
  '2',
  '0',
  '0',
  '2',
  '0',
  '2',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '2',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'sqm': ['117',
  '600.2',
  '891',
  '350.5',
  '600.2',
  '308',
  '746.5',
  '410',
  '392',
  '410',
  '105',
  '860',
  '377.3',
  '392',
  '400.5',
  '410',
  '410',
  '309',
  '780',
  '168',
  '410',
  '891',
  '410',
  '410',
  '498',
  '300',
  '328',
  '410',
  '504',
  '176',
  '168',
  '498',
  '410',
  '498',
  '176',
  '184',
  '410',
  '463',
  '184',
  '498',
  '176',
  '410',
  '504',
  '410',
  '609.8',
  '498',
  '168',
  '270',
  '410',
  '400.5',
  '184',
  '892',
  '325',
  '377.3',
  '410',
  '410',
  '780',
  '410',
  '498',
  '105',
  '504',
  '410',
  '345',
  '410',
  '185',
  '176'],
 'year_built': ['2023',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2023',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2023',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2023',
  '2023',
  '2024',
  '2024',
  '2024',
  '2023',
  '2023',
  '2024',
  '2024',
  '2023',
  '2024',
  '2023',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2023',
  '2023',
  '2024',
  '2024',
  '2023',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2024',
  '2023',
  '2024',
  '2024',
  '2024',
  '2024',
  '2023',
  '2023'],
 'features': [['أخرى', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهرباء متاحة'],
  ['أخرى', 'أمن 24 ساعة', 'الكهرباء متاحة']],
 'city': ['Cairo',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Cairo',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Cairo',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Cairo',
  'Cairo',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Cairo',
  'Cairo',
  'Mansoura',
  'Mansoura',
  'Cairo',
  'Mansoura',
  'Cairo',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Cairo',
  'Cairo',
  'Mansoura',
  'Mansoura',
  'Cairo',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Cairo',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Mansoura',
  'Cairo',
  'Cairo'],
 'governorate': ['Cairo',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Cairo',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Cairo',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Cairo',
  'Cairo',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Cairo',
  'Cairo',
  'Dakahlia',
  'Dakahlia',
  'Cairo',
  'Dakahlia',
  'Cairo',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Cairo',
  'Cairo',
  'Dakahlia',
  'Dakahlia',
  'Cairo',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Cairo',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Dakahlia',
  'Cairo',
  'Cairo'],
 'address': ['Building MM Floor Ground floor Unit MMRTG24B Maspero mall Cairo Cairo Cairo Egypt',
  'Building ZH3M71 Unit ZH3M71 Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH1C69 Floor Ground floor Unit ZH1C69 Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZHM219 Floor Ground floor Unit ZHM219B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M72 Unit ZH3M72 Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZHC226 Floor Ground floor Unit ZHC226B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M106 Unit ZH3M106 Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M211 Unit ZH3M211A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M239 Unit ZH3M239A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M217 Unit ZH3M217B Zahya Mansoura (m) Dakahlia Egypt',
  'Building MBT Floor 10th floor Unit MBTAD103 Maspero Business Tower Nile Heights Cairo Cairo Cairo Egypt',
  'Building ZH1C70 Floor Ground floor Unit ZH1C70 Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZHM253 Floor Ground floor Unit ZHM253A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZHM254 Floor Ground Unit ZHM254D Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZHM223 Floor Ground floor Unit ZHM223A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M221 Unit ZH3M221B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M216 Unit ZH3M216B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZHC225 Floor Ground floor Unit ZHC225A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH1C156 Floor Ground floor Unit ZH1C156 Zahya Mansoura (m) Dakahlia Egypt',
  'Building NH Floor 2nd floor Unit NHAD0205 Maspero Business Tower Nile Heights Cairo Cairo Cairo Egypt',
  'Building ZH3M205 Unit ZH3M205B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH1C69 Floor Ground floor Unit ZH1C69 Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M209 Unit ZH3M209B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M222 Unit ZH3M222B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M233 Unit ZH3M233B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZHC224 Floor Ground floor Unit ZHC224A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH1C325B Floor Ground floor Unit ZH1C325B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M209 Unit ZH3M209B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M244 Unit ZH3M244C Zahya Mansoura (m) Dakahlia Egypt',
  'Building NH Floor 3rd floor Unit NHAD0306 Maspero Business Tower Nile Heights Cairo Cairo Cairo Egypt',
  'Building NH Floor 2nd floor Unit NHAD0205 Maspero Business Tower Nile Heights Cairo Cairo Cairo Egypt',
  'Building ZH3M232 Unit ZH3M232B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M212 Unit ZH3M212A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M235 Unit ZH3M235A Zahya Mansoura (m) Dakahlia Egypt',
  'Building MM Floor Ground floor Unit MMFBG22B Maspero mall Cairo Cairo Cairo Egypt',
  'Building NH Floor 5th floor Unit NHAD0505 Maspero Business Tower Nile Heights Cairo Cairo Cairo Egypt',
  'Building ZH3M197 Unit ZH3M197A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH1C320B Floor Ground floor Unit ZH1C320B Zahya Mansoura (m) Dakahlia Egypt',
  'Building NH Floor 6th floor Unit NHAD0602 Maspero Business Tower Nile Heights Cairo Cairo Cairo Egypt',
  'Building ZH3M229 Unit ZH3M229B Zahya Mansoura (m) Dakahlia Egypt',
  'Building NH Floor 3rd floor Unit NHAD0306 Maspero Business Tower Nile Heights Cairo Cairo Cairo Egypt',
  'Building ZH3M197 Unit ZH3M197A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M250 Unit ZH3M250A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M214 Unit ZH3M214A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M73 Unit ZH3M73 Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M228 Unit ZH3M228B Zahya Mansoura (m) Dakahlia Egypt',
  'Building NH Floor 2nd floor Unit NHAD0202 Maspero Business Tower Nile Heights Cairo Cairo Cairo Egypt',
  'Building MBT Floor Ground floor Unit MBTRT027 Maspero Business Tower Nile Heights Cairo Cairo Cairo Egypt',
  'Building ZH3M201 Unit ZH3M201A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZHM223 Floor Ground floor Unit ZHM223A Zahya Mansoura (m) Dakahlia Egypt',
  'Building NH Floor 7th floor Unit NHAD0705 Maspero Business Tower Nile Heights Cairo Cairo Cairo Egypt',
  'Building ZH1C71 Floor Ground floor Unit ZH1C71 Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH1C323B Floor Ground floor Unit ZH1C323B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZHM253 Floor Ground floor Unit ZHM253A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M203 Unit ZH3M203B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M216 Floor Ground floor Unit ZH3M216A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH1C156 Floor Ground floor Unit ZH1C156 Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M208 Unit ZH3M208A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M229 Unit ZH3M229B Zahya Mansoura (m) Dakahlia Egypt',
  'Building MBT Floor 10th floor Unit MBTAD103 Maspero Business Tower Nile Heights Cairo Cairo Cairo Egypt',
  'Building ZH3M246 Unit ZH3M246A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M217 Unit ZH3M217B Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZHM219 Floor Ground floor Unit ZHM219A Zahya Mansoura (m) Dakahlia Egypt',
  'Building ZH3M226 Unit ZH3M226A Zahya Mansoura (m) Dakahlia Egypt',
  'Building NH Floor 2nd floor Unit NHAD0201 Maspero Business Tower Nile Heights Cairo Cairo Cairo Egypt',
  'Building MM Floor Ground floor Unit MMFBG22B Maspero mall Cairo Cairo Cairo Egypt'],
 'description': ['يُعد ماسبيرو مول وجهة فريدة لتجارب التسوق ونمط الحياة في قلب القاهرة. يقع في مثلث ماسبيرو، ويُعتبر أيقونة في وسط المدينة، حيث يقدّم تجارب تسوق لا تُنسى، ومأكولات شهية، ومجموعة متنوعة من وسائل الترفيه التي تضمن لك قضاء أوقات ممتعة.واستنادًا إلى إرث يمتد لآلاف السنين، يسعى ماسبيرو مول إلى تدشين عصر جديد من التجارب العصرية التي تهدف إلى إبهار الأجيال القادمة',
  'بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكني في مدينة المنصورة الجديدة، نتطلع بشوق إلى رؤية المستقبل بمشروعٍ مُزدهرٍ في قلب العاصمة الجديدة الواعدة للدلتا. ومع وعدٍ بمستقبلٍ جديدٍ زاخرٍ بالتطورات التكنولوجية، وفرصٍ تجاريةٍ وتجاريةٍ وتجزئة، سيُسهم مشروع "زاهية" في تعزيز وضوح رؤية هذه المدينة الجديدة من خلال توفير منازل تُوفر لسكانها تجاربَ معيشيةً متكاملة.',
  'بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكني في مدينة المنصورة الجديدة، نتطلع بشوق إلى رؤية المستقبل بمشروعٍ مُزدهرٍ في قلب العاصمة الجديدة الواعدة للدلتا. ومع وعدٍ بمستقبلٍ جديدٍ زاخرٍ بالتطورات التكنولوجية، وفرصٍ تجاريةٍ وتجاريةٍ وتجزئة، سيُسهم مشروع "زاهية" في تعزيز وضوح رؤية هذه المدينة الجديدة من خلال توفير منازل تُوفر لسكانها تجاربَ معيشيةً متكاملة.',
  'بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكني في مدينة المنصورة الجديدة، نتطلع بشوق إلى رؤية المستقبل بمشروعٍ مُزدهرٍ في قلب العاصمة الجديدة الواعدة للدلتا. ومع وعدٍ بمستقبلٍ جديدٍ زاخرٍ بالتطورات التكنولوجية، وفرصٍ تجاريةٍ وتجاريةٍ وتجزئة، سيُسهم مشروع "زاهية" في تعزيز وضوح رؤية هذه المدينة الجديدة من خلال توفير منازل تُوفر لسكانها تجاربَ معيشيةً متكاملة.',
  'بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكني في مدينة المنصورة الجديدة، نتطلع بشوق إلى رؤية المستقبل بمشروعٍ مُزدهرٍ في قلب العاصمة الجديدة الواعدة للدلتا. ومع وعدٍ بمستقبلٍ جديدٍ زاخرٍ بالتطورات التكنولوجية، وفرصٍ تجاريةٍ وتجاريةٍ وتجزئة، سيُسهم مشروع "زاهية" في تعزيز وضوح رؤية هذه المدينة الجديدة من خلال توفير منازل تُوفر لسكانها تجاربَ معيشيةً متكاملة.',
  'بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكني في مدينة المنصورة الجديدة، نتطلع بشوق إلى رؤية المستقبل بمشروعٍ مُزدهرٍ في قلب العاصمة الجديدة الواعدة للدلتا. ومع وعدٍ بمستقبلٍ جديدٍ زاخرٍ بالتطورات التكنولوجية، وفرصٍ تجاريةٍ وتجاريةٍ وتجزئة، سيُسهم مشروع "زاهية" في تعزيز وضوح رؤية هذه المدينة الجديدة من خلال توفير منازل تُوفر لسكانها تجاربَ معيشيةً متكاملة.',
  'بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكني في مدينة المنصورة الجديدة، نتطلع بشوق إلى رؤية المستقبل بمشروعٍ مُزدهرٍ في قلب العاصمة الجديدة الواعدة للدلتا. ومع وعدٍ بمستقبلٍ جديدٍ زاخرٍ بالتطورات التكنولوجية، وفرصٍ تجاريةٍ وتجاريةٍ وتجزئة، سيُسهم مشروع "زاهية" في تعزيز وضوح رؤية هذه المدينة الجديدة من خلال توفير منازل تُوفر لسكانها تجاربَ معيشيةً متكاملة.',
  'بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكني في مدينة المنصورة الجديدة، نتطلع بشوق إلى رؤية المستقبل بمشروعٍ مُزدهرٍ في قلب العاصمة الجديدة الواعدة للدلتا. ومع وعدٍ بمستقبلٍ جديدٍ زاخرٍ بالتطورات التكنولوجية، وفرصٍ تجاريةٍ وتجاريةٍ وتجزئة، سيُسهم مشروع "زاهية" في تعزيز وضوح رؤية هذه المدينة الجديدة من خلال توفير منازل تُوفر لسكانها تجاربَ معيشيةً متكاملة.',
  'بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكني في مدينة المنصورة الجديدة، نتطلع بشوق إلى رؤية المستقبل بمشروعٍ مُزدهرٍ في قلب العاصمة الجديدة الواعدة للدلتا. ومع وعدٍ بمستقبلٍ جديدٍ زاخرٍ بالتطورات التكنولوجية، وفرصٍ تجاريةٍ وتجاريةٍ وتجزئة، سيُسهم مشروع "زاهية" في تعزيز وضوح رؤية هذه المدينة الجديدة من خلال توفير منازل تُوفر لسكانها تجاربَ معيشيةً متكاملة.',

### Include 2025 real_estates

In [ ]:
# real_estates_data = collect_real_estate_data(links)
# real_estates_data

## Include 2025

### Exporting the data

In [ ]:
# real_estates_df = pd.read_json(r"../data/processed/real_estates_data.json")
# real_estates_df # convert to a dataset

,name,price,property_type,bedrooms,bathrooms,sqm,year_built,features,city,governorate,address,description
0,Maspero mall,"17,886,000 ج م","تجاري, مبنى البيع بالتجزئة / مول",0,0,117.0,2023,"[أخرى, أمن 24 ساعة, الكهرباء متاحة]",Cairo,Cairo,Building MM Floor Ground floor Unit MMRTG24B M...,يُعد ماسبيرو مول وجهة فريدة لتجارب التسوق ونمط...
1,Zahya,"17,536,000 ج م","سكني, فيلا",3,2,600.2,2024,"[اللوبي, أمن 24 ساعة, الكهرباء متاحة]",Mansoura,Dakahlia,Building ZH3M71 Unit ZH3M71 Zahya Mansoura (m)...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
2,Zahya,"22,024,000 ج م","سكني, فيلا",3,0,891.0,2024,"[اللوبي, أمن 24 ساعة, الكهرباء متاحة]",Mansoura,Dakahlia,Building ZH1C69 Floor Ground floor Unit ZH1C69...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
3,Zahya,"10,249,000 ج م","سكني, توين هاوس",3,0,350.5,2024,"[اللوبي, أمن 24 ساعة, الكهرباء متاحة]",Mansoura,Dakahlia,Building ZHM219 Floor Ground floor Unit ZHM219...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
4,Zahya,"17,478,000 ج م","سكني, فيلا",3,2,600.2,2024,"[اللوبي, أمن 24 ساعة, الكهرباء متاحة]",Mansoura,Dakahlia,Building ZH3M72 Unit ZH3M72 Zahya Mansoura (m)...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
...,...,...,...,...,...,...,...,...,...,...,...,...
61,Zahya,"10,612,000 ج م","سكني, توين هاوس",3,0,410.0,2024,"[اللوبي, أمن 24 ساعة, الكهرباء متاحة]",Mansoura,Dakahlia,Building ZH3M217 Unit ZH3M217B Zahya Mansoura ...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
62,Zahya,"10,209,000 ج م","سكني, توين هاوس",3,0,345.0,2024,"[اللوبي, أمن 24 ساعة, الكهرباء متاحة]",Mansoura,Dakahlia,Building ZHM219 Floor Ground floor Unit ZHM219...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
63,Zahya,"10,669,000 ج م","سكني, توين هاوس",3,0,410.0,2024,"[اللوبي, أمن 24 ساعة, الكهرباء متاحة]",Mansoura,Dakahlia,Building ZH3M226 Unit ZH3M226A Zahya Mansoura ...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
64,Maspero Business Tower Nile Heights,"12,026,000 ج م","تجاري, مكتب",0,0,185.0,2023,"[أخرى, أمن 24 ساعة, مجتمع مسور, الكهرباء متاحة]",Cairo,Cairo,Building NH Floor 2nd floor Unit NHAD0201 Masp...,من الإطلالات الخلابة على أفق القاهرة المتألّق ...
65,Maspero mall,"28,692,000 ج م","تجاري, مبنى البيع بالتجزئة / مول",0,0,176.0,2023,"[أخرى, أمن 24 ساعة, الكهرباء متاحة]",Cairo,Cairo,Building MM Floor Ground floor Unit MMFBG22B M...,يُعد ماسبيرو مول وجهة فريدة لتجارب التسوق ونمط...

In [ ]:
# #Export it as a csv file
# real_estates_df.to_csv("../data/processed/real_estates_data.csv", index=False)

I scrapped more 283 rows, so the final output is 1183 rows

In [ ]:
# re_df = pd.read_csv(r"../data/processed/old_real_estates.csv")
# re_df_77 = pd.read_csv(r"../data/processed/real_estates_data(1).csv")
# re_df_206 = pd.read_csv(r"../data/processed/real_estates_data(2).csv")
#
# # Concatenate all dataframes vertically (row-wise)
# re_df = pd.concat([re_df, re_df_77, re_df_206], ignore_index=True)
#
# re_df

,name,price,property_type,bedrooms,bathrooms,sqm,year_built,features,city,governorate,address,description
0,Maspero mall,"17,886,000 ج م","تجاري, مبنى البيع بالتجزئة / مول",0,0,117.00,2023,"['أخرى', 'أمن 24 ساعة', 'الكهرباء متاحة']",Cairo,Cairo,Building MM Floor Ground floor Unit MMRTG24B M...,يُعد ماسبيرو مول وجهة فريدة لتجارب التسوق ونمط...
1,Zahya,"17,536,000 ج م","سكني, فيلا",3,2,600.20,2024,"['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة']",Mansoura,Dakahlia,Building ZH3M71 Unit ZH3M71 Zahya Mansoura (m)...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
2,Zahya,"22,024,000 ج م","سكني, فيلا",3,0,891.00,2024,"['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة']",Mansoura,Dakahlia,Building ZH1C69 Floor Ground floor Unit ZH1C69...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
3,Zahya,"10,249,000 ج م","سكني, توين هاوس",3,0,350.50,2024,"['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة']",Mansoura,Dakahlia,Building ZHM219 Floor Ground floor Unit ZHM219...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
4,Zahya,"17,478,000 ج م","سكني, فيلا",3,2,600.20,2024,"['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة']",Mansoura,Dakahlia,Building ZH3M72 Unit ZH3M72 Zahya Mansoura (m)...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
...,...,...,...,...,...,...,...,...,...,...,...,...
344,T- Residences,"2,668,259 EGP","Residential, Apartment",3,1,120.00,2024,"['24 Hour Security', 'Electricity Available', ...",North Coast,Matrouh,Building C-12 Floor 6 Unit 62 T- Residences No...,"""Torec Developments is a subsidiary of the New..."
345,Alamain (Latin District),"3,226,000 EGP","Residential, Apartment",1,0,94.61,2025,"['Other', 'Security Gate', 'Electricity Availa...",North Coast,Alexandria,Building D15 Floor 7 Unit Z02-CL07-D15-X7-07-0...,Latini by Saudi Egyptian Developers (SED) – Ne...
346,Downtown commercial,"20,540,000 EGP","Commercial, Retail",0,0,200.00,2025,"['Other', '24 Hour Security', 'Electricity Ava...",Mersa Matruh,Matrouh,Building DT01 Floor Ground floor Unit DTRG0130...,Designed to be an integrated residential and c...
347,Alamain (Latin District),"6,512,000 EGP","Residential, Apartment",4,0,213.53,2025,"['Other', 'Security Gate', 'Electricity Availa...",North Coast,Alexandria,Building C06 Floor 1 Unit Z05-CL11-C06-M7-01-0...,Latini by Saudi Egyptian Developers (SED) – Ne...
348,New Garden City,"6,956,000 EGP","Residential, Apartment",2,0,166.00,2025,"['Gate Community', 'Natural Gas Available']",New Administrative Capital,Cairo,Building G645 Floor 7th floor Unit G64576 New ...,"To live in a world, where you can see and sens..."

In [ ]:
# re_df.to_csv("../data/processed/real_estates_data(new).csv", index=False)

## Except 2025

In [ ]:
re_df = pd.read_csv(r"../data/processed/real_estates_data(new).csv")
re_df_except_2025 = pd.read_csv(r"../data/processed/old_real_estates.csv")

re_df = pd.concat([re_df, re_df_except_2025], ignore_index=True)

re_df

,name,price,property_type,bedrooms,bathrooms,sqm,year_built,features,city,governorate,address,description
0,Alamain (Latin District),"6,594,000 EGP","Residential, Apartment",1,0,92.86,2025,"['Other', 'Security Gate', 'Electricity Availa...",North Coast,Alexandria,Building F04 Floor 6 Unit Z02-CL05-F04-X7-06-1...,Latini by Saudi Egyptian Developers (SED) – Ne...
1,Beachfront Tower - B1,"66,104,000 EGP","Residential, Apartment",3,3,398.00,2025,['Other'],Mersa Matruh,Matrouh,Building BTB1 Floor 9th floor Unit BTB1091 Bea...,Explore a lifestyle that allows you to have yo...
2,PODIA,"12,824,000 EGP","Commercial, Office",0,0,93.00,2025,"['Other', '24 Hour Security', 'Fire Alarm', 'G...",Cairo,Cairo,Floor 13th Unit MPO-1304-A Bin ZayedNorth PODI...,Launched by Menassat Developments in cooperati...
3,Mazarine Apartment,"12,857,000 EGP","Residential, Apartment",3,3,252.00,2025,"['24 Hour Security', 'Electricity Available']",Mersa Matruh,Matrouh,Building MZCS15 Floor 3rd floor Unit MZCS1531 ...,The name ‘Mazarine’ came to fruition based on ...
4,Alamain (Latin District),"8,721,000 EGP","Residential, Apartment",3,0,209.42,2025,"['Other', 'Security Gate', 'Electricity Availa...",North Coast,Alexandria,Building E01 Floor 1 Unit Z02-CL09-E01-X4-01-0...,One of the main districts in this new city nei...
...,...,...,...,...,...,...,...,...,...,...,...,...
1244,Zahya,"10,612,000 ج م","سكني, توين هاوس",3,0,410.00,2024,"['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة']",Mansoura,Dakahlia,Building ZH3M217 Unit ZH3M217B Zahya Mansoura ...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
1245,Zahya,"10,209,000 ج م","سكني, توين هاوس",3,0,345.00,2024,"['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة']",Mansoura,Dakahlia,Building ZHM219 Floor Ground floor Unit ZHM219...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
1246,Zahya,"10,669,000 ج م","سكني, توين هاوس",3,0,410.00,2024,"['اللوبي', 'أمن 24 ساعة', 'الكهرباء متاحة']",Mansoura,Dakahlia,Building ZH3M226 Unit ZH3M226A Zahya Mansoura ...,بصفتنا شركة عقارية رائدة تُعنى ببناء مشروع سكن...
1247,Maspero Business Tower Nile Heights,"12,026,000 ج م","تجاري, مكتب",0,0,185.00,2023,"['أخرى', 'أمن 24 ساعة', 'مجتمع مسور', 'الكهربا...",Cairo,Cairo,Building NH Floor 2nd floor Unit NHAD0201 Masp...,من الإطلالات الخلابة على أفق القاهرة المتألّق ...
1248,Maspero mall,"28,692,000 ج م","تجاري, مبنى البيع بالتجزئة / مول",0,0,176.00,2023,"['أخرى', 'أمن 24 ساعة', 'الكهرباء متاحة']",Cairo,Cairo,Building MM Floor Ground floor Unit MMFBG22B M...,يُعد ماسبيرو مول وجهة فريدة لتجارب التسوق ونمط...

In [ ]:
re_df.to_csv("../data/processed/real_estates_data_except_2025.csv", index=False)