# Predictive Modeling

## Prepare my workspace

In [2]:
# Import needed libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load the data
re_df = pd.read_csv(r"D:\Data science project\Data science\Codveda-internship\Level 1\Task 2\processed_real_estate.csv")

# preview the data
print("Real estates data:\n")
re_df

Real estates data:

,name,sqm,year_built,Price(EGP),Price/Sqm,has_main_facilities,has_security_features,has_parking_safety,has_building_facilities,has_other_features,...,propertySubType_Office,propertySubType_Others(very rare),propertySubType_Retail,Is sqm outlier,Is Price/Sqm outlier,Is Price(EGP) outlier,Is FloorNumber outlier,log(sqm),log(price),log(price/sqm)
0,Alamain (Latin District),92.86,2025,6594000,71010.1228,1,1,0,0,1,...,0,0,0,False,False,False,False,4.531093,15.701671,11.170578
1,Beachfront Tower - B1,398.00,2025,66104000,166090.4523,0,0,0,0,1,...,0,0,0,True,True,True,False,5.986452,18.006740,12.020288
2,PODIA,93.00,2025,12824000,137892.4731,0,1,1,0,1,...,1,0,0,False,True,False,True,4.532599,16.366829,11.834229
3,Mazarine Apartment,252.00,2025,12857000,51019.8413,1,1,0,0,0,...,0,0,0,False,False,False,False,5.529429,16.369399,10.839970
4,Alamain (Latin District),209.42,2025,8721000,41643.5870,1,1,0,0,1,...,0,0,0,False,False,False,False,5.344342,15.981244,10.636903
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851,Alamain (Latin District),177.47,2025,5678000,31994.1399,1,1,0,0,1,...,0,0,0,False,False,False,False,5.178802,15.552110,10.373308
852,Jade Park,692.00,2025,25292000,36549.1329,1,0,1,1,0,...,0,0,0,True,False,True,False,6.539586,17.045999,10.506413
853,Mamsha Avenue,171.00,2025,6137000,35888.8889,1,1,0,0,1,...,0,0,0,False,False,False,False,5.141664,15.629847,10.488183
854,Alamain (Latin District),207.58,2025,5933000,28581.7516,1,1,0,0,1,...,0,0,0,False,False,False,False,5.335517,15.596041,10.260524
855,PODIA,42.00,2025,5446000,129666.6667,0,1,1,0,1,...,0,1,0,False,True,False,False,3.737670,15.510392,11.772722

## Regression

### Pick the wanted features only

In [5]:
drop_cols = ["sqm","Price(EGP)","Price/Sqm",
             "year_built","FloorNumber","BuildingNumber",
             "UnitNumber","Is FloorNumber outlier","LowFloor",
             "Bedroom_0","Bathroom_0","city_Cairo",
             "governorate_Cairo","propertyCategory_Residential",
             "propertySubType_Apartment"] # The unnecessary columns, and first dummy from every categorical column of dummies for full rank dummies

reg_df = re_df.drop(drop_cols, axis=1) # drop these columns
reg_df

,name,has_main_facilities,has_security_features,has_parking_safety,has_building_facilities,has_other_features,HighFloor,MidFloor,has_modern,has_facilities,...,propertySubType_Attached Houses,propertySubType_Office,propertySubType_Others(very rare),propertySubType_Retail,Is sqm outlier,Is Price/Sqm outlier,Is Price(EGP) outlier,log(sqm),log(price),log(price/sqm)
0,Alamain (Latin District),1,1,0,0,1,0,1,1,1,...,0,0,0,0,False,False,False,4.531093,15.701671,11.170578
1,Beachfront Tower - B1,0,0,0,0,1,1,0,0,1,...,0,0,0,0,True,True,True,5.986452,18.006740,12.020288
2,PODIA,0,1,1,0,1,1,0,0,0,...,0,1,0,0,False,True,False,4.532599,16.366829,11.834229
3,Mazarine Apartment,1,1,0,0,0,0,1,0,1,...,0,0,0,0,False,False,False,5.529429,16.369399,10.839970
4,Alamain (Latin District),1,1,0,0,1,0,0,0,0,...,0,0,0,0,False,False,False,5.344342,15.981244,10.636903
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851,Alamain (Latin District),1,1,0,0,1,0,0,0,0,...,0,0,0,0,False,False,False,5.178802,15.552110,10.373308
852,Jade Park,1,0,1,1,0,0,1,0,1,...,0,0,0,0,True,False,True,6.539586,17.045999,10.506413
853,Mamsha Avenue,1,1,0,0,1,0,1,0,1,...,0,0,0,0,False,False,False,5.141664,15.629847,10.488183
854,Alamain (Latin District),1,1,0,0,1,0,1,1,1,...,0,0,0,0,False,False,False,5.335517,15.596041,10.260524
855,PODIA,0,1,1,0,1,0,1,0,0,...,0,0,1,0,False,True,False,3.737670,15.510392,11.772722

In [ ]:
# Set X, and y
X = reg_df.drop(["name","log(price)","Is sqm outlier", "Is Price/Sqm outlier",
                 "Is Price(EGP) outlier"],axis= 1)
y = reg_df["log(price)"]

X # Split outliers from non-outliers

,has_main_facilities,has_security_features,has_parking_safety,has_building_facilities,has_other_features,HighFloor,MidFloor,has_modern,has_facilities,has_green_view,...,governorate_Alexandria,governorate_Dakahlia,governorate_Matrouh,propertyCategory_Commercial,propertySubType_Attached Houses,propertySubType_Office,propertySubType_Others(very rare),propertySubType_Retail,log(sqm),log(price/sqm)
0,1,1,0,0,1,0,1,1,1,0,...,1,0,0,0,0,0,0,0,4.531093,11.170578
1,0,0,0,0,1,1,0,0,1,1,...,0,0,1,0,0,0,0,0,5.986452,12.020288
2,0,1,1,0,1,1,0,0,0,1,...,0,0,0,1,0,1,0,0,4.532599,11.834229
3,1,1,0,0,0,0,1,0,1,1,...,0,0,1,0,0,0,0,0,5.529429,10.839970
4,1,1,0,0,1,0,0,0,0,1,...,1,0,0,0,0,0,0,0,5.344342,10.636903
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851,1,1,0,0,1,0,0,0,0,1,...,1,0,0,0,0,0,0,0,5.178802,10.373308
852,1,0,1,1,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,6.539586,10.506413
853,1,1,0,0,1,0,1,0,1,1,...,0,0,0,0,0,0,0,0,5.141664,10.488183
854,1,1,0,0,1,0,1,1,1,0,...,1,0,0,0,0,0,0,0,5.335517,10.260524
855,0,1,1,0,1,0,1,0,0,1,...,0,0,0,1,0,0,1,0,3.737670,11.772722